### ISSUE TITLE
Start indexing the workflows tht use containers

### ISSUE THREAD

**Issue by ypriverol** [BioContainers/biocontainers-backend#17]
@chakrabandla we should start indexing in the registry with the new pipeline the workflows that are here in this file https://github.com/BioContainers/workflows/blob/master/workflows.csv. The file contains a name of the user that create the workflow, a possible name, description and the url of the github repo. We should be able to go to each repo and depending on the type of workflow index in biocontainer database. This includes the following: 

- [ ] Read the main workflow file for nextflow or cwl. 
- [ ] Read the metadata of the workflow. 
- [ ] Check if the workflow use Biocontainers. 
- [ ] In case an specific biocontainers is use, we should be able to make a link between the container and the workflow. 

The final idea is to have a final report for each container about all the workflows where it has been used. 

Lets try to discuss this here in details before coding.

**Comment by chakrabandla** [comment]
done right?

**Comment by ypriverol** [comment]
Yes
