### ISSUE TITLE
Registry down?

### ISSUE THREAD

**Issue by schorlton** [BioContainers/biocontainers-backend#23]
Is the biocontainers registry down? Couldn't find a gitter to reach out and don't have twitter. Was working a couple weeks ago, hasn't been working for the past couple of days.
I'm getting a Server Error when trying to search the registry. Specifically, my console is showing a 522 error with message: `Access to XMLHttpRequest at 'https://api.biocontainers.pro//api/ga4gh/v2/tools?offset=0&limit=30&all_fields_search=pysam&sort_field=default&sort_order=asc' from origin 'https://biocontainers.pro' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Thanks for your amazing work!

**Comment by ypriverol** [comment]
Is down because we are doing some maintenance in the backend. Sorry for the inconvenience.
