### ISSUE TITLE
Missing properties in Tool & ToolVersion responses

### ISSUE THREAD

**Issue by chakrabandla** [BioContainers/biocontainers-backend#3]
Following properties are yet to be implemented in Tool & ToolVersion responses

**Tool** :
aliases
meta_version
contains  : "array"
has_checker
checker_url
verified_source
signed

**Tool_version** :
name
image
registry_url
image_name
descriptor_type  => array of enum: "CWL" , "WDL", "NFL"
containerfile
meta_version
verified
verified_source

**Comment by ypriverol** [comment]
Hi @chakrabandla see my comments: 

> Following properties are yet to be implemented in Tool & ToolVersion responses
> 
> **Tool** :

> aliases

*Use the tool name *

> meta_version

*Version of the tool , latest version*

> contains : "array"

*List of tools in the container* if the tool is a single tool container then put in the array the tool. 

> has_checker

Empty. 

> checker_url

Empty. 

> verified_source

Empty. 

> signed

True for all Tools. 
> 

> **Tool_version** :
> name

Name of the tool. 
> image

List of images. 

> registry_url

here we should use url of biocontainers: biocontainers.pro/registry/tool_Id/tool_version/

> image_name

> descriptor_type => array of enum: "CWL" , "WDL", "NFL"

EMpty for now.

> containerfile

Here the container file Dockerfile or Conda recipe. 

> meta_version

Here the version of the tool. 

> verified

true 

> verified_source

**Comment by ypriverol** [comment]
@bgruening input here would be good. ?

**Comment by bgruening** [comment]
> descriptor_type => array of enum: "CWL" , "WDL", "NFL"

We should request a `plain` or something.

I agree with the rest. Thanks!

**Comment by ypriverol** [comment]
@bgruening would be great if we said now GW -> Galaxy wrapper. That makes sense for you.

**Comment by bgruening** [comment]
But our containers are completely agnostic, right? We do not put useless stuff into a container on purpose :) Galaxy can use all containers either way.

**Comment by ypriverol** [comment]
ok
